stages:
  tokenize:
    cmd: python code/0_tokenize.py
    deps:
      - code/0_tokenize.py
      - data/dataset/chembl_31_chemreps.txt
    outs:
      - data/tokenized
  train:
    cmd: python code/1_train.py
    params: 
      - learning_rate
      - latent_dim
    deps:
      - code/1_train.py
      - data/tokenized
    outs:
      - model/
      - metrics/train/metrics.csv
  evaluate:
    cmd: python code/2_evaluate.py
    deps:
      - code/2_evaluate.py
      - data/tokenized
      - model
    metrics:
      - metrics/test/scores.json
plots:
  - loss: 
      y:
        metrics/train/metrics.csv: [loss, val_loss]
      x_label: Epoch
      y_label: Loss
      title: Loss
  - accuracy: 
      y:
        metrics/train/metrics.csv: [accuracy, val_accuracy]
      x_label: Epoch
      y_label: Accuracy
      title: Accuracy
