stages:
  install:
    cmd: zsh code/0_install.sh
    deps:
      - code/0_install.sh
    outs:
      - env
  download:
    cmd: python code/1_download.py
    deps:
      - env
      - code/1_download.py
      - https://ftp.ebi.ac.uk/pub/databases/chembl/ChEMBLdb/releases/chembl_32/chembl_32_chemreps.txt.gz
    outs:
      - data/raw
  tokenize:
    cmd: python code/2_tokenize.py
    deps:
      - code/2_tokenize.py
      - data/raw
    outs:
      - data/tokenized
  train:
    cmd: python code/3_train.py
    params: 
      - learning_rate
      - latent_dim
    deps:
      - code/3_train.py
      - data/tokenized
    outs:
      - model/
      - metrics/train/metrics.csv
  evaluate:
    cmd: python code/4_evaluate.py
    deps:
      - code/4_evaluate.py
      - data/tokenized
      - model
    metrics:
      - metrics/test/scores.json
plots:
  - loss: 
      y:
        metrics/train/metrics.csv: [loss, val_loss]
      x_label: Epoch
      y_label: Loss
      title: Loss
  - accuracy: 
      y:
        metrics/train/metrics.csv: [accuracy, val_accuracy]
      x_label: Epoch
      y_label: Accuracy
      title: Accuracy
